### ISSUE TITLE
Define timeout in the Spec

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#116]
Future tools like dogserve will benefit on a task-defined timeout.

Proposal:

```yml
- task: example
  desctiption: This task can't run for more than 60 seconds
  timeout: 60 # always use seconds
  code: <code-goes-here>
```

The `timeout` directive needs to be added to the Dogfile Spec.
