### ISSUE TITLE
Running subshells introduces strange behaviour

### ISSUE THREAD

**Issue by leemachin** [dogtools/dog#129]
I have many Dog tasks that open new shells (thanks to Docker). Example:

```yaml
- task: prod-api-sh
  description: Shell into the api container in production
  code: convox exec $(convox ps | grep api | cut -f1 -d' ') sh
```

The code is pretty much the same as running `docker exec -it api_container sh`.

This works fine, but the resulting shell behaves strangely. Random control codes are inserted straight after the prompt, and signals go straight to Dog rather than the subshell. This means that hitting Ctrl+C to terminate a command inside the container actually terminates the container itself. Arrow keys don't work, neither do the usual movement shortcuts (Ctrl+A, Ctrl+E), and colours don't work either.
