### ISSUE TITLE
Provide parameters to tasks

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#5]
Dogfile.yml defines if task parameters are mandatory and if they have a default value.

**Comment by xsb** [comment]
```
parameters:
  - name: varname1 # variable without default value
  - name: varname2 # variable with default value
    default: value2
```

**Comment by xsb** [comment]
I documented this feature in the [Dogfile Format Reference](https://github.com/xsb/dog/blob/master/DOGFILE_REFERENCE.md#parameters) but I'm still not sure about it.

The other option I like is to natively support environment variables and forget about parameters. If we go with env vars, the format will look like this:

```yml
  env:
    - ANIMAL
    - CITY
    - PLANET
```

Then **dog** will require the input, in a similar format as docker run does:

`$ dog taskname -e ANIMAL=dog -e CITY=barcelona -e PLANET=earth`

Parameters Pros:
- Flexible
- Input can be restricted

Parameters Cons:
- Requires a new YAML object type
- Only works with sh/bash scripts

Env vars Pros:
- Universal, will work with any executor type
- Can be exposed in the environment and then there is no need to use the cli arguments to provide them

Env vars Cons:
- Less flexible, we won't be able to define a list of allowed values (I'm not sure about this feature anyway)

What's your view on this?
/cc @marc-gr @gchaincl @n-marshall

**Comment by xsb** [comment]
We can do a mix of both. Support only environment variables but:
- Make them required (but not necessary to pass them through the CLI)
- Implement default values and value arrays

**Comment by xsb** [comment]
After discussing this a bit more with @marc-gr we would like to modify the Spec to remove *parameter* and add *env*, this is an example:

```yml
- task: task-with-vars
  description: Task with environment variables
  env:
    - CITY: Barcelona
    - ANIMAL:
         - dog
         - cat
         - human
  run: |
    echo "Animal is $ANIMAL"
    echo "City is $CITY"
```

Barcelona is the default value for CITY and ["dog","cat","human"] are the accepted values for ANIMAL.

dog would be launched like this:

```sh
dog task-with-vars -e ANIMAL=dog     # OK
dog task-with-vars -e ANIMAL=dolphin # FAIL
```

What do you think @slapresta @marc-gr @n-marshall ?

**Comment by xsb** [comment]
I created #63 so we can have both env vars and parameters

**Comment by xsb** [comment]
@marc-gr @slapresta @Vidimensional and myself had a [meeting](https://twitter.com/xavi_xsb/status/764045354056749056) today and decided a few things:
- We will remove the `-e` flag, the only way to provide values to tasks from the CLI is using params

- The way it will work from the CLI is like in this example:

```
dog where-am-i planet=Earth galaxy=milkyway
```

- The Dogfile Spec will look like this example

```yml
- task: where-am-i
  params:
    - name: planet
      default: Earth
      regex: <some-regex-here> # mutually exclusive with "choices"
      choices:
        - Neptune
        - Mars
        - Saturn
```
- Internal Implementation: A task with params will receive their values as positional arguments in the same order as they are defined in the params array in the Dogfile. Which means that the CLI uses key=value args, the Dogfile uses YAML objects and the task receives positional args.

Notes:
- The *regex* option will be implemented later, and will be mutually exclusive with the *choices* directive.
- We are still not sure if we need to implement positional arguments (as in: `dog task arg1 arg2`).
