### ISSUE TITLE
Implement workdir directive

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#69]
Sets the working directory for the task. An absolute path can be provided. If a relative path is provided instead, it's considered relative to the ubication of the Dogfile.

Example

```yml
  task: hello-script
  description: Run hello.sh script inside the scripts/ directory
  workdir: ./scripts/
  run: ./hello.sh
```
