### ISSUE TITLE
Dog doesn't support interactive tasks execution

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#86]
Example Dogfile

```yml
- task: interactive-task
  description: Interactive Task
  run: |
    read A
    echo $A
```

Run interactive task

```
$ dog interactive-task
$
```
